"""initial schema

Revision ID: 550747571357
Revises: 
Create Date: 2026-05-27 14:34:59.585659+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '550747571357'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_results',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('gold_set_item_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('judge_model', sa.String(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_agent_prompt', 'eval_results', ['agent_id', 'prompt_version'], unique=False)
    op.create_index('ix_eval_gold_item', 'eval_results', ['gold_set_item_id'], unique=False)
    op.create_index(op.f('ix_eval_results_created_at'), 'eval_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_eval_results_gold_set_item_id'), 'eval_results', ['gold_set_item_id'], unique=False)
    op.create_index(op.f('ix_eval_results_id'), 'eval_results', ['id'], unique=False)
    op.create_index(op.f('ix_eval_results_run_id'), 'eval_results', ['run_id'], unique=False)
    op.create_index('ix_eval_run', 'eval_results', ['run_id'], unique=False)
    op.create_table('grants',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('summary_en', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('portal', sa.Enum('BMBF', 'EXIST', 'KFW', 'EIC', 'HORIZON', 'BAYERN', 'NRW', 'BW', name='grantportal'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'UPCOMING', 'ROLLING', name='grantstatus'), nullable=False),
    sa.Column('sector', sa.Enum('DEEPTECH', 'CLEANTECH', 'HEALTH', 'BIOTECH', 'SAAS', 'HARDWARE', 'AI_ML', 'FINTECH', 'OTHER', name='sector'), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('federal_state', sa.String(), nullable=True),
    sa.Column('funding_min_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('funding_max_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(1024), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_doc_id', sa.String(), nullable=True),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', name='uq_grants_source_url')
    )
    op.create_index(op.f('ix_grants_created_at'), 'grants', ['created_at'], unique=False)
    op.create_index('ix_grants_deadline', 'grants', ['deadline'], unique=False)
    op.create_index(op.f('ix_grants_id'), 'grants', ['id'], unique=False)
    op.create_index(op.f('ix_grants_portal'), 'grants', ['portal'], unique=False)
    op.create_index('ix_grants_portal_status', 'grants', ['portal', 'status'], unique=False)
    op.create_index(op.f('ix_grants_sector'), 'grants', ['sector'], unique=False)
    op.create_index('ix_grants_sector_status', 'grants', ['sector', 'status'], unique=False)
    op.create_index(op.f('ix_grants_source_doc_id'), 'grants', ['source_doc_id'], unique=False)
    op.create_index(op.f('ix_grants_source_url'), 'grants', ['source_url'], unique=False)
    op.create_index(op.f('ix_grants_status'), 'grants', ['status'], unique=False)
    op.create_index(op.f('ix_grants_title'), 'grants', ['title'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_name_version')
    )
    op.create_index(op.f('ix_prompt_versions_content_hash'), 'prompt_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_prompt_versions_created_at'), 'prompt_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_versions_id'), 'prompt_versions', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_is_active'), 'prompt_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_versions_name'), 'prompt_versions', ['name'], unique=False)
    op.create_table('startups',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.Enum('DEEPTECH', 'CLEANTECH', 'HEALTH', 'BIOTECH', 'SAAS', 'HARDWARE', 'AI_ML', 'FINTECH', 'OTHER', name='sector'), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'PRE_SEED', 'SEED', 'SERIES_A', 'GROWTH', name='startupstage'), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('federal_state', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('frs_scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startups_created_at'), 'startups', ['created_at'], unique=False)
    op.create_index(op.f('ix_startups_id'), 'startups', ['id'], unique=False)
    op.create_index(op.f('ix_startups_owner_user_id'), 'startups', ['owner_user_id'], unique=False)
    op.create_index('ix_startups_sector_stage', 'startups', ['sector', 'stage'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('short_term_memory', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('long_term_memory_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('episodic_memory', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_created_at'), 'agent_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_sessions_id'), 'agent_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_is_active'), 'agent_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_sessions_owner_user_id'), 'agent_sessions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_startup_id'), 'agent_sessions', ['startup_id'], unique=False)
    op.create_index('ix_sessions_startup', 'agent_sessions', ['startup_id'], unique=False)
    op.create_index('ix_sessions_user', 'agent_sessions', ['owner_user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('grant_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SLACK', 'IN_APP', name='alertchannel'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'grant_id', 'channel', name='uq_alerts_triple')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_grant_id'), 'alerts', ['grant_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index('ix_alerts_pending', 'alerts', ['notification_sent_at'], unique=False)
    op.create_index(op.f('ix_alerts_startup_id'), 'alerts', ['startup_id'], unique=False)
    op.create_table('funding_roadmaps',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('agent_session_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_roadmaps_created_at'), 'funding_roadmaps', ['created_at'], unique=False)
    op.create_index(op.f('ix_funding_roadmaps_id'), 'funding_roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_funding_roadmaps_is_active'), 'funding_roadmaps', ['is_active'], unique=False)
    op.create_index(op.f('ix_funding_roadmaps_startup_id'), 'funding_roadmaps', ['startup_id'], unique=False)
    op.create_index('ix_roadmaps_startup', 'funding_roadmaps', ['startup_id'], unique=False)
    op.create_table('grant_applications',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('grant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('section_scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apps_grant', 'grant_applications', ['grant_id'], unique=False)
    op.create_index('ix_apps_startup_status', 'grant_applications', ['startup_id', 'status'], unique=False)
    op.create_index(op.f('ix_grant_applications_created_at'), 'grant_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_grant_applications_grant_id'), 'grant_applications', ['grant_id'], unique=False)
    op.create_index(op.f('ix_grant_applications_id'), 'grant_applications', ['id'], unique=False)
    op.create_index(op.f('ix_grant_applications_startup_id'), 'grant_applications', ['startup_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('thumbs_up', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('output_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_agent_thumbs', 'user_feedback', ['agent_id', 'thumbs_up'], unique=False)
    op.create_index('ix_feedback_session', 'user_feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_created_at'), 'user_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_feedback_id'), 'user_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_user_feedback_owner_user_id'), 'user_feedback', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_session_id'), 'user_feedback', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedback_session_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_owner_user_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_created_at'), table_name='user_feedback')
    op.drop_index('ix_feedback_session', table_name='user_feedback')
    op.drop_index('ix_feedback_agent_thumbs', table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_grant_applications_startup_id'), table_name='grant_applications')
    op.drop_index(op.f('ix_grant_applications_id'), table_name='grant_applications')
    op.drop_index(op.f('ix_grant_applications_grant_id'), table_name='grant_applications')
    op.drop_index(op.f('ix_grant_applications_created_at'), table_name='grant_applications')
    op.drop_index('ix_apps_startup_status', table_name='grant_applications')
    op.drop_index('ix_apps_grant', table_name='grant_applications')
    op.drop_table('grant_applications')
    op.drop_index('ix_roadmaps_startup', table_name='funding_roadmaps')
    op.drop_index(op.f('ix_funding_roadmaps_startup_id'), table_name='funding_roadmaps')
    op.drop_index(op.f('ix_funding_roadmaps_is_active'), table_name='funding_roadmaps')
    op.drop_index(op.f('ix_funding_roadmaps_id'), table_name='funding_roadmaps')
    op.drop_index(op.f('ix_funding_roadmaps_created_at'), table_name='funding_roadmaps')
    op.drop_table('funding_roadmaps')
    op.drop_index(op.f('ix_alerts_startup_id'), table_name='alerts')
    op.drop_index('ix_alerts_pending', table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_grant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_sessions_user', table_name='agent_sessions')
    op.drop_index('ix_sessions_startup', table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_startup_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_owner_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_is_active'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_created_at'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('ix_startups_sector_stage', table_name='startups')
    op.drop_index(op.f('ix_startups_owner_user_id'), table_name='startups')
    op.drop_index(op.f('ix_startups_id'), table_name='startups')
    op.drop_index(op.f('ix_startups_created_at'), table_name='startups')
    op.drop_table('startups')
    op.drop_index(op.f('ix_prompt_versions_name'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_is_active'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_created_at'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_content_hash'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_grants_title'), table_name='grants')
    op.drop_index(op.f('ix_grants_status'), table_name='grants')
    op.drop_index(op.f('ix_grants_source_url'), table_name='grants')
    op.drop_index(op.f('ix_grants_source_doc_id'), table_name='grants')
    op.drop_index('ix_grants_sector_status', table_name='grants')
    op.drop_index(op.f('ix_grants_sector'), table_name='grants')
    op.drop_index('ix_grants_portal_status', table_name='grants')
    op.drop_index(op.f('ix_grants_portal'), table_name='grants')
    op.drop_index(op.f('ix_grants_id'), table_name='grants')
    op.drop_index('ix_grants_deadline', table_name='grants')
    op.drop_index(op.f('ix_grants_created_at'), table_name='grants')
    op.drop_table('grants')
    op.drop_index('ix_eval_run', table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_run_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_gold_set_item_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_created_at'), table_name='eval_results')
    op.drop_index('ix_eval_gold_item', table_name='eval_results')
    op.drop_index('ix_eval_agent_prompt', table_name='eval_results')
    op.drop_table('eval_results')
    # ### end Alembic commands ###
