"""scrape_runs table

Revision ID: f87cd99cba85
Revises: 6f72ff401213
Create Date: 2026-05-27 20:22:07.817419+00:00

NOTE: Alembic autogenerate proposed dropping `ix_grants_embedding_hnsw`,
`ix_grants_title_trgm`, and `ix_grants_summary_trgm` because those indexes
are not represented in SQLModel metadata (we built them with raw SQL in
revision 6f72ff401213). Those drops are NOT what we want — the indexes
are real, in use, and must stay. We deleted them from this revision.

This is a known Alembic limitation: it can't see indexes created via
`op.execute(...)`. Whenever we add new tables, autogenerated revisions
will keep proposing the same spurious drops. The convention going forward
is to manually strip them from each new revision.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f87cd99cba85"
down_revision: str | Sequence[str] | None = "6f72ff401213"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `grantportal` already exists from revision 550747571357 — reuse it
    # via create_type=False to avoid `DuplicateObject` on re-runs.
    grantportal_enum = postgresql.ENUM(
        "BMBF", "EXIST", "KFW", "EIC", "HORIZON", "BAYERN", "NRW", "BW",
        name="grantportal",
        create_type=False,
    )
    # We create the types explicitly here, then reference them in the column
    # declarations with create_type=False to avoid SQLAlchemy double-creating
    # during op.create_table.
    trigger_enum = postgresql.ENUM(
        "SCHEDULED", "MANUAL", "CLI",
        name="scraperuntrigger",
        create_type=False,
    )
    status_enum = postgresql.ENUM(
        "RUNNING", "SUCCESS", "PARTIAL", "FAILED",
        name="scraperunstatus",
        create_type=False,
    )
    postgresql.ENUM(
        "SCHEDULED", "MANUAL", "CLI",
        name="scraperuntrigger",
    ).create(op.get_bind(), checkfirst=True)
    postgresql.ENUM(
        "RUNNING", "SUCCESS", "PARTIAL", "FAILED",
        name="scraperunstatus",
    ).create(op.get_bind(), checkfirst=True)

    op.create_table(
        "scrape_runs",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portal", grantportal_enum, nullable=False),
        sa.Column("trigger", trigger_enum, nullable=False),
        sa.Column("status", status_enum, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("inserted", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("skipped_unchanged", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("embedded", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scrape_runs_created_at"), "scrape_runs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_scrape_runs_id"), "scrape_runs", ["id"], unique=False)
    op.create_index(op.f("ix_scrape_runs_portal"), "scrape_runs", ["portal"], unique=False)
    op.create_index(
        "ix_scrape_runs_portal_started", "scrape_runs", ["portal", "started_at"], unique=False
    )
    op.create_index(op.f("ix_scrape_runs_status"), "scrape_runs", ["status"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_scrape_runs_status"), table_name="scrape_runs")
    op.drop_index("ix_scrape_runs_portal_started", table_name="scrape_runs")
    op.drop_index(op.f("ix_scrape_runs_portal"), table_name="scrape_runs")
    op.drop_index(op.f("ix_scrape_runs_id"), table_name="scrape_runs")
    op.drop_index(op.f("ix_scrape_runs_created_at"), table_name="scrape_runs")
    op.drop_table("scrape_runs")
    # Drop our own enums but leave `grantportal` alone (other tables use it).
    op.execute("DROP TYPE IF EXISTS scraperunstatus")
    op.execute("DROP TYPE IF EXISTS scraperuntrigger")
